### ISSUE TITLE
ParseError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by polikin** [Tokimon/vanillajs-browser-helpers#20]
When I tried to import addClass(`import addClass from 'vanillajs-browser-helpers/addClass';`), I get this error: `ParseError: 'import' and 'export' may appear only with 'sourceType: module` with browserify/babel.

**Comment by Tokimon** [comment]
Hi.
Generally the main files are build with es6 modules and needs transpilation via tools like Rollup or Webpack (unless you use them in browsers that support modules).
If you want the transpiled commonJS vesion import the ES5 version:  
`import addClass from 'vanillajs-browser-helpers/es5/addClass';`
